"""empty message

Revision ID: e45de00516ce
Revises: 
Create Date: 2020-08-23 01:42:48.954905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45de00516ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PatientDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.Column('healthinsuranceid', sa.Integer(), nullable=False),
    sa.Column('healthcareid', sa.Integer(), nullable=False),
    sa.Column('countryid', sa.Integer(), nullable=False),
    sa.Column('numberid', sa.Integer(), nullable=False),
    sa.Column('regionid', sa.Integer(), nullable=False),
    sa.Column('cityid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PatientDetails')
    # ### end Alembic commands ###
